title: Alexander Simson
email: alex@simsons.se
description: >- # this means to ignore newlines until "baseurl:"
  Alexander Simson - Senior iOS Developer from Sweden.
baseurl: ""
url: "https://alexsimson.se"
twitter_username: alexandersimson
github_username:  aalekz

# Build settings
theme: plainwhite

plainwhite:
  name: Alexander Simson
  tagline: iOS Developer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: alexandersimson
    github: aalekz
    linkedIn: in/alexandersimson

remote_theme: thelehhman/plainwhite-jekyll

plugins:
   - jekyll-seo-tag

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
